variables:
  - group: Cyon

trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: InstallSSHKey@0
    inputs:
      knownHostsEntry: $(SSH_KNOWN_HOSTS)
      sshPublicKey: $(SSH_PUBLIC_KEY)
      sshKeySecureFile: sshKeySecureFile
    displayName: 'SSH Key einrichten'

  - script: |
      scp -r ./* bfh@bfh.finklenburg.ch:/home/finklenb/public_html/bfh/
    displayName: 'Deploy to Cyon'